api:
  replicaCount: 3
  image:
    repository: ghcr.io/ojasik/mini-platform
    tag: "17ed5ea98319eb39ad02462820a359313b506aca"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
redis:
  enabled: true
  replicaCount: 1
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 6379
    targetPort: 6379
  external:
    host: ""
    port: 6379
ingress:
  enabled: true
  className: "traefik"
  host: mini-platform.local
